include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    sort_pub_dependencies: false
    public_member_api_docs: false
    one_member_abstracts: false
