import 'package:flutter/material.dart';

/// Flutter icons GithubIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GithubIcon
///      fonts:
///       - asset: fonts/GithubIcon.ttf
///
///
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
class GithubIcon {
  GithubIcon._internal();

  static const _kFontFam = 'GithubIcon';

  static const IconData github = IconData(0xf308, fontFamily: _kFontFam);
}
